# Generated by Django 5.0.1 on 2026-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='zoo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='zooportal_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['uuid'], name='dog_uuid_d66744_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['zooportal_id'], name='dog_zooport_9cfb80_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['zoo_hash'], name='dog_zoo_has_44297f_idx'),
        ),
        migrations.RunSQL(
            # При откате (zero) заполняем NULL перед возвратом NOT NULL
            sql=migrations.RunSQL.noop,
            reverse_sql="""
                UPDATE dog SET uuid = 'placeholder_' || id::text WHERE uuid IS NULL;
                UPDATE dog SET zoo_hash = 'placeholder_' || id::text WHERE zoo_hash IS NULL;
            """,
        ),
    ]