# Generated by Django 5.0.1 on 2026-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0002_alter_dog_uuid_alter_dog_zoo_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTaskProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Импорт данных',
                'verbose_name_plural': 'Панель импорта',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='dog',
            name='zooportal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
