# Generated by Django 5.0.1 on 2026-05-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0003_importtaskproxy_alter_dog_zooportal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zooportal_show_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('show_type', models.CharField(choices=[('pk', 'Монопородная ПК'), ('kchk', 'Монопородная КЧК'), ('speciality', 'Специализированная'), ('sport', 'Спортивные соревнования'), ('world', 'World/Euro Dog Show'), ('other', 'Не учитывается')], default='other', max_length=20)),
                ('multiplier', models.FloatField(default=0.0)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=500, null=True)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('judges', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('results_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'db_table': 'show_event',
                'managed': True,
                'indexes': [models.Index(fields=['event_date'], name='show_event_event_d_6d4b75_idx'), models.Index(fields=['zooportal_show_id'], name='show_event_zooport_dfa63b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('show_class', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('titles_won', models.CharField(blank=True, max_length=500, null=True)),
                ('rating_points', models.IntegerField(default=0)),
                ('catalog_count', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('nomination', models.CharField(default='main', max_length=20)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_results', to='dogs_module.dog')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dogs_module.showevent')),
            ],
            options={
                'verbose_name': 'Результат выставки',
                'verbose_name_plural': 'Результаты выставок',
                'db_table': 'show_result',
                'managed': True,
                'indexes': [models.Index(fields=['dog', 'event'], name='show_result_dog_id_3c5cd1_idx')],
            },
        ),
    ]
