# Generated by Django 5.0.1 on 2026-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0004_dog_rating_dog_rating_updated_at_showevent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showresult',
            unique_together={('event', 'dog')},
        ),
    ]
