# Generated by Django 5.0.1 on 2026-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0005_alter_showresult_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'managed': True, 'ordering': ['-test_date'], 'verbose_name': 'Медицинская запись', 'verbose_name_plural': 'Медицинские записи'},
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('ofa_number__isnull', False)), fields=('dog', 'ofa_number'), name='unique_dog_ofa_number'),
        ),
    ]
