# Generated by Django 5.0.1 on 2026-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0006_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo_yadisk_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь фото на Яндекс.Диске'),
        ),
    ]
