# Generated by Django 5.0.1 on 2026-05-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0007_dog_photo_yadisk_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo_yadisk_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Публичная ссылка фото на Яндекс.Диске'),
        ),
    ]
