# Generated by Django 5.0.1 on 2026-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0008_dog_photo_yadisk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
