# Generated by Django 5.0.1 on 2026-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0009_dog_photo_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo_yadisk_url',
            field=models.TextField(blank=True, null=True, verbose_name='Публичная ссылка фото на Яндекс.Диске'),
        ),
    ]
