# Generated by Django 5.0.1 on 2026-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0010_alter_dog_photo_yadisk_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['sex', 'year_of_birth'], name='dog_sex_1f7a76_idx'),
        ),
    ]
