# Generated by Django 5.0.1 on 2026-06-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0011_dog_dog_sex_1f7a76_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='ofa_appnum',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
