# Generated by Django 5.0.1 on 2026-06-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0012_dog_ofa_appnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowYearlyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('nomination', models.CharField(default='main', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_ratings', to='dogs_module.dog')),
            ],
            options={
                'db_table': 'show_yearly_rating',
                'indexes': [models.Index(fields=['year', 'nomination'], name='yearly_rating_leaderboard_idx')],
                'unique_together': {('dog', 'year', 'nomination')},
            },
        ),
    ]
