# Generated by Django 5.0.1 on 2026-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0013_showyearlyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birth_litter',
            field=models.IntegerField(blank=True, db_column='birth_litter_id', null=True),
        ),
        migrations.DeleteModel(
            name='Litter',
        ),
    ]
