# Generated by Django 5.0.1 on 2026-08-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_module', '0014_alter_dog_birth_litter_delete_litter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBestrussianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestrussian_ratings', to='dogs_module.dog')),
            ],
            options={
                'verbose_name': 'Рейтинг Best Russian Dog',
                'verbose_name_plural': 'Рейтинги Best Russian Dog',
                'db_table': 'dog_bestrussian_rating',
                'managed': True,
                'unique_together': {('dog', 'year')},
            },
        ),
    ]
