# Generated by Django 5.0.1 on 2025-12-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=200)),
                ('resource_id', models.CharField(max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('bio_key', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BreedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('content_key', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('history', 'history'), ('character', 'character'), ('care', 'care'), ('grooming', 'grooming'), ('feeding', 'feeding')], max_length=50)),
                ('videos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['title_key'],
            },
        ),
        migrations.CreateModel(
            name='BreedStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('content_key', models.CharField(blank=True, max_length=200)),
                ('fci_number', models.CharField(blank=True, max_length=50)),
                ('illustrations', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-approved_date'],
            },
        ),
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('charter', 'charter'), ('regulation', 'regulation'), ('standard', 'standard'), ('form', 'form')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_key', models.CharField(max_length=200)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('event_type', models.CharField(blank=True, choices=[('exhibition', 'exhibition'), ('seminar', 'seminar'), ('meeting', 'meeting'), ('other', 'other')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('description_key', models.CharField(blank=True, max_length=255)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_highlight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(blank=True, max_length=200)),
                ('bio_key', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='judges/')),
                ('materials', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prefix', models.CharField(blank=True, max_length=200)),
                ('site_url', models.URLField(blank=True)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('monitor_enabled', models.BooleanField(default=False)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_screenshot', models.ImageField(blank=True, null=True, upload_to='kennel_checks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('benefit_type', models.CharField(choices=[('discount', 'discount'), ('access', 'access'), ('service', 'service'), ('priority', 'priority')], max_length=20)),
                ('membership_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_key'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('membership_type', models.CharField(choices=[('physical', 'physical'), ('legal', 'legal')], max_length=10)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['membership_type', 'annual_fee'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_key', models.CharField(max_length=200)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='protected/')),
                ('url', models.URLField(blank=True)),
                ('required_membership', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField()),
                ('page', models.CharField(default='general', max_length=100)),
                ('locale', models.CharField(default='ru', max_length=10)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'key'],
                'indexes': [models.Index(fields=['key'], name='core_conten_key_b13c76_idx'), models.Index(fields=['page'], name='core_conten_page_1fd301_idx'), models.Index(fields=['locale'], name='core_conten_locale_71830e_idx'), models.Index(fields=['page', 'locale'], name='core_conten_page_80ecde_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registered_name', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('pedigree_number', models.CharField(blank=True, max_length=200)),
                ('microchip', models.CharField(blank=True, max_length=200)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('is_champion', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whelped_litters', to='core.dog')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_litters', to='core.dog')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='core.kennel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.judge'),
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whelped_at', models.DateTimeField(blank=True, null=True)),
                ('puppies_count', models.IntegerField(blank=True, null=True)),
                ('notes_key', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('announced', 'announced'), ('born', 'born'), ('sold', 'sold')], default='announced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters_as_dam', to='core.dog')),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters', to='core.kennel')),
                ('sire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters_as_sire', to='core.dog')),
            ],
            options={
                'ordering': ['-whelped_at'],
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('description_key', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='core.judge')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('check_frequency', models.IntegerField(default=7)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_screenshot', models.ImageField(blank=True, null=True, upload_to='site_checks/')),
                ('updates', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.kennel')),
            ],
            options={
                'ordering': ['-last_check'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('is_nkp_member', models.BooleanField(default=False)),
                ('membership_type', models.CharField(blank=True, choices=[('physical', 'physical'), ('legal', 'legal')], max_length=10, null=True)),
                ('membership_started_at', models.DateTimeField(blank=True, null=True)),
                ('membership_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.kennel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(max_length=200)),
                ('lead_key', models.CharField(blank=True, max_length=255)),
                ('body_key', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to='core.user')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.user')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='kennel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kennels', to='core.user'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='core.user'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('membership', 'membership'), ('litter_registration', 'litter_registration'), ('kennel_registration', 'kennel_registration'), ('document_request', 'document_request'), ('complaint', 'complaint'), ('other', 'other')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done'), ('rejected', 'rejected')], default='new', max_length=20)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievements/')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='core.dog')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.user')),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_nkp_member'], name='core_user_is_nkp__c04ffb_idx'),
        ),
    ]
