# Generated by Django 5.0.1 on 2025-12-16 16:31

import core.models_django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.FileField(blank=True, null=True, upload_to='svgs/', validators=[core.models_django.validate_svg], verbose_name='SVG-картинка')),
            ],
            options={
                'verbose_name': 'Быстрая ссылка',
                'verbose_name_plural': 'Быстрые ссылки',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['name'], 'verbose_name': 'Породный эксперт', 'verbose_name_plural': 'Породные эксперты'},
        ),
        migrations.RemoveField(
            model_name='judge',
            name='bio_key',
        ),
        migrations.AddField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='materials',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='judges/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='rank',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='JudgeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('info', models.JSONField(blank=True, default=list, verbose_name='Информация')),
                ('additional_info_title', models.JSONField(blank=True, default=list, verbose_name='Доп. информация заголовок')),
                ('additional_info_text', models.JSONField(blank=True, default=list, verbose_name='Доп. информация текст')),
                ('work_directions', models.JSONField(blank=True, default=list, verbose_name='Направления работы')),
                ('initiative_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('initiative_state', models.CharField(blank=True, choices=[('active', 'Активный'), ('in developing', 'В разработке'), ('planning', 'Планирование')], max_length=20, null=True, verbose_name='Состояние')),
                ('initiative_text', models.TextField(max_length=500, verbose_name='Текст')),
                ('initiative_stack', models.JSONField(default=list, verbose_name='Стэк')),
                ('sidebar_text', models.CharField(max_length=200, verbose_name='Текст')),
                ('sidebar_achievements', models.JSONField(default=list, verbose_name='Достижения')),
                ('kennel_url', models.URLField(blank=True, verbose_name='Ссылка на питомник')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='core.kennel', verbose_name='Питомник')),
            ],
            options={
                'verbose_name': 'Породный эксперт (подробно)',
                'verbose_name_plural': 'Породные эксперты (подробно)',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_id',
            field=models.ForeignKey(blank=True, db_column='judge_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge', to='core.judgedetails', verbose_name='Детальная информация'),
        ),
    ]
