# Generated by Django 4.2.7 on 2025-12-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_judgedetails_initiatives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts_at'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчёт о мероприятии', 'verbose_name_plural': 'Отчёты о мероприятиях'},
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='results',
            field=models.JSONField(blank=True, default=list, verbose_name='Результаты'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='Видео'),
        ),
    ]
