# Generated by Django 4.2.7 on 2025-12-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_options_alter_eventreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['-date'], 'verbose_name': 'Семинар', 'verbose_name_plural': 'Семинары'},
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('membership', 'Членство'), ('litter_registration', 'Регистрация помёта'), ('kennel_registration', 'Регистрация питомника'), ('document_request', 'Запрос документов'), ('complaint', 'Жалоба'), ('other', 'Другое')], max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Рассмотрена'), ('rejected', 'Отклонена')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_key',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('exhibition', 'Выставка'), ('seminar', 'Семинар'), ('meeting', 'Встреча'), ('other', 'Другое')], max_length=20, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.judge', verbose_name='Породные эксперты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_key',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='materials',
            field=models.JSONField(blank=True, default=list, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='core.judge', verbose_name='Спикер'),
        ),
        migrations.CreateModel(
            name='EventReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_reports/videos/', verbose_name='Видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='core.eventreport', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Видео отчёта',
                'verbose_name_plural': 'Видео отчёта',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='event_reports/photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_items', to='core.eventreport', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Фото отчёта',
                'verbose_name_plural': 'Фото отчёта',
                'ordering': ['created_at'],
            },
        ),
    ]
