# Generated by Django 4.2.7 on 2025-12-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_seminar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='videos',
        ),
    ]
