# Generated by Django 4.2.7 on 2026-01-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventreport_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Документ клуба', 'verbose_name_plural': 'Документы клуба'},
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='description_key',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='document_type',
            field=models.CharField(choices=[('charter', 'устав'), ('regulation', 'обычный'), ('standard', 'стандарт'), ('form', 'форма')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='title_key',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
