# Generated by Django 4.2.7 on 2026-01-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clubdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubdocument',
            options={'ordering': ['document_type', 'order', '-uploaded_at'], 'verbose_name': 'Документ клуба', 'verbose_name_plural': 'Документы клуба'},
        ),
        migrations.AddField(
            model_name='clubdocument',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='clubdocument',
            name='document_type',
            field=models.CharField(choices=[('charter', 'устав'), ('regulation', 'регламент'), ('standard', 'стандарт'), ('form', 'форма')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
