# Generated by Django 4.2.7 on 2026-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clubdocument_options_clubdocument_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='Владельцев сибирских хаски')),
                ('kennels_count', models.PositiveIntegerField(default=0, verbose_name='Питомников')),
                ('dogs_in_archive_count', models.PositiveIntegerField(default=0, verbose_name='Собак в архиве')),
                ('regions_count', models.PositiveIntegerField(default=0, verbose_name='Регионов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика клуба',
                'verbose_name_plural': 'Статистика клуба',
            },
        ),
    ]
