# Generated by Django 4.2.7 on 2026-02-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clubstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рабочая группа',
                'verbose_name_plural': 'Рабочие группы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Член клуба', 'verbose_name_plural': 'Члены клуба'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='bio_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='board/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='working_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.workinggroup', verbose_name='Рабочая группа'),
        ),
    ]
