# Generated by Django 5.0.1 on 2026-04-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workinggroup_alter_boardmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сезона')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название гонки')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('organizers', models.CharField(blank=True, max_length=255, verbose_name='Организаторы')),
                ('judge', models.CharField(blank=True, max_length=255, verbose_name='Судья')),
                ('distances', models.CharField(blank=True, max_length=255, verbose_name='Дистанции (например: 4,2 км · 8,3 км)')),
                ('is_qualifying', models.BooleanField(default=True, verbose_name='Квалификационная гонка')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Количество участников')),
                ('results_file', models.FileField(blank=True, null=True, upload_to='data/race_results/', verbose_name='JSON-файл с результатами')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='core.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Гонка',
                'verbose_name_plural': 'Гонки',
                'ordering': ['-date'],
            },
        ),
    ]
