# Generated by Django 5.0.1 on 2026-04-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_season_race'),
        ('core', '0013_sitebannersettings'),
    ]

    operations = [
    ]
