# Generated by Django 5.0.1 on 2026-04-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_0013_season_race_0013_sitebannersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebannersettings',
            options={'verbose_name': 'Настройки баннера сайта', 'verbose_name_plural': 'Настройки баннера сайта'},
        ),
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('open', 'Открыта регистрация'), ('done', 'Завершена')], default='planned', max_length=20, verbose_name='Статус гонки'),
        ),
    ]
