# Generated by Django 5.0.1 on 2026-04-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sitebannersettings_options_race_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(default='Президент НКП', max_length=255, verbose_name='Должность')),
                ('subtitle', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('main_text', models.TextField(verbose_name='Основной текст')),
                ('highlight_text', models.TextField(blank=True, verbose_name='Текст выделенного блока')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('reception_days', models.CharField(blank=True, max_length=255, verbose_name='Приёмные дни')),
                ('socials', models.CharField(blank=True, max_length=255, verbose_name='Соцсети')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный президент')),
            ],
            options={
                'verbose_name': 'Президент',
                'verbose_name_plural': 'Президент',
            },
        ),
        migrations.CreateModel(
            name='PresidentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Год')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.president')),
            ],
            options={
                'verbose_name': 'Достижение президента',
                'verbose_name_plural': 'Достижения президента',
                'ordering': ['sort_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='PresidentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Иконка')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной бейдж')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.president')),
            ],
            options={
                'verbose_name': 'Бейдж президента',
                'verbose_name_plural': 'Бейджи президента',
                'ordering': ['sort_order'],
            },
        ),
    ]
